name: Python CI/CD Pipeline

on:
  push:
    branches: [main]  # Trigger the workflow on push to the main branch
  pull_request:
    branches: [main]  # Trigger the workflow for pull requests to the main branch

jobs:
  lint:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install flake8 for linting

      - name: Run flake8
        run: |
          flake8 --max-line-length=79  # Run flake8 with line length set to 79

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest for testing
          pip install pandas  # Install pandas for test dependencies

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run tests with pytest
